---
- name: Copy ssh key
  hosts: all
  tasks:
    - name: Add authorized keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: '{{ lookup("file", lookup("env", "HOME") + "/.ssh/id_rsa.pub") }}'
